spring:
  #mysql
  datasource:
    url: jdbc:mysql://172.20.19.73:3306/shiro_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #redis
  redis:
    host: 172.20.19.73
    port: 6379
    database: 3
    timeout: 30000
    password: '1234567'
token:
  refresh:
    interval: 3600